name = "AgentClerk"
client_id = "23e9d3c89a55ccc5d8736bdc69bdc014"
application_url = "https://web-service-production-c889.up.railway.app"

[access_scopes]
scopes = "read_products,read_orders,read_customers,read_content,read_themes"

[auth]
redirect_urls = ["https://web-service-production-c889.up.railway.app/auth/callback"]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["orders/create", "orders/paid"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["products/create", "products/update", "products/delete"]
  uri = "/webhooks"

[app_proxy]
url = "https://web-service-production-c889.up.railway.app/api"
subpath = "agentclerk"
subpath_prefix = "apps"
